version: "2"

services:
    nginx:
        build: ./nginx/
        hostname: "${PROJECT_NAME}_nginx"
        container_name: "${PROJECT_NAME}_nginx"
        environment:
            - "VIRTUAL_HOST=${VHOST}"
            - "NGINX_PORT=${NGINX_PORT}"
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "${PROJECT_ROOT}:/var/www/html"
        networks:
            - server
        depends_on:
            - php
        command: [nginx-debug, '-g', 'daemon off;']

    php:
        build: ./php/
        hostname: "${PROJECT_NAME}_php"
        container_name: "${PROJECT_NAME}_php"
        expose:
            - 9000
        volumes:
            - "${PROJECT_ROOT}:/var/www/html"
        networks:
            - database
            - server
        depends_on:
            - mysql

    mysql:
        image: mysql:latest
        hostname: "${PROJECT_NAME}_db"
        container_name: "${PROJECT_NAME}_db"
        volumes:
            - data:/var/lib/mysql
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        hostname: "${PROJECT_NAME}_phpmyadmin"
        container_name: "${PROJECT_NAME}_phpmyadmin"
        ports:
            - "${PHPMYADMIN_PORT}:80"
        networks:
            - database
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql

volumes:
    data:

networks:
    database:
    server:

